#!/bin/sh -e

# export the path to be sure it's set properly
export PATH="/opt/local/sbin:/opt/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/gonano/sbin:/opt/gonano/bin"

# command to run nginx
exec nginx -c /opt/gonano/etc/narc.conf
