#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

execute "bring down vip" do
  command "ifconfig redd0:0 down"
end

execute "remove persistance" do
  command "rm -f /etc/nanoinit.d/redd00"
end
