#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gomicro/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# Close the firewall
if payload[:platform] == 'production'

  execute "close up the firewall" do
    command "/etc/microinit.d/portal-iptables stop"
    not_if { !File.exist?('/etc/microinit.d/portal-iptables') }
  end

  execute "remove persistence" do
    command "rm -f /etc/microinit.d/portal-iptables"
    not_if { !File.exist?('/etc/microinit.d/portal-iptables') }
  end

end

# Stop portal
service 'portal' do
  action :disable
  not_if { !Dir.exist?('/etc/service/portal') }
end

# Remove portal runit definition
directory '/etc/service/portal' do
  action :delete
  not_if { !Dir.exist?('/etc/service/portal') }
end

# Stop nginx
service 'nginx' do
  action :disable
  not_if { !Dir.exist?('/etc/service/nginx') }
end

# Remove nginx runit definition
directory '/etc/service/nginx' do
  action :delete
  not_if { !Dir.exist?('/etc/service/nginx') }
end

# Stop narc
service 'narc' do
  action :disable
  not_if { !Dir.exist?('/etc/service/narc') }
end

# Remove narc runit definition
directory '/etc/service/narc' do
  action :delete
  not_if { !Dir.exist?('/etc/service/narc') }
end
