#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gonano/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

# Close the firewall
if payload[:platform] == 'production'

  execute "close up the firewall" do
    command "iptables -D INPUT -p tcp -m tcp --dport 8443 -j ACCEPT"
    not_if { `iptables -L | grep 8443`.empty? }
  end

  execute "remove persistence" do
    command "rm -f /etc/nanoinit.d/portal-iptables"
  end

end

# Remove the IP if provided
if payload[:ips]

  execute "bring down vip" do
    command "ifconfig redd0:0 down"
  end

  execute "remove persistance" do
    command "rm -f /etc/nanoinit.d/redd00"
  end
end

# Stop portal
service 'portal' do
  action :disable
end

# Remove portal runit definition
directory '/etc/service/portal' do
  action :delete
end

# Stop narc
service 'narc' do
  action :disable
end

# Remove narc runit definition
directory '/etc/service/narc' do
  action :delete
end
