#!/usr/bin/env ruby

# hookit is installed as a bundled app, so we need bundler to load it for us
$:.unshift  '/opt/gomicro/hookit/vendor/bundle'
require 'bundler/setup'

# load hookit/setup to bootstrap hookit and import the dsl
require 'hookit/setup'

local_portal_md5 = execute "local portal md5" do
  command "cat /var/microbox/portal.md5"
  not_if { ! ::File.exists? "/var/microbox/portal.md5" }
end

aws_portal_md5 = execute "aws portal md5" do
  command "curl \
      -f \
      -k \
      https://s3.amazonaws.com/tools.microbox.cloud/portal/linux/amd64/portal.md5 \
        | tee /tmp/portal.md5"
end

if local_portal_md5 != aws_portal_md5
  # Stop portal
  service 'portal' do
    action :disable
    not_if { !Dir.exist?('/etc/service/portal') }
  end

  execute "Download portal" do
    command "curl \
      -f \
      -k \
      -o /usr/local/bin/portal \
      https://s3.amazonaws.com/tools.microbox.cloud/portal/linux/amd64/portal"
  end

  execute "Chmod portal" do
    command "chmod 755 /usr/local/bin/portal"
  end

  service 'portal' do
    action :enable
    not_if { !Dir.exist?('/etc/service/portal') }
  end

  execute "Finalize update" do
    command "mv /tmp/portal.md5 /var/microbox/portal.md5"
  end
end

local_hooks_md5 = execute "local hooks md5" do
  command "cat /var/microbox/hooks.md5"
  not_if { ! ::File.exists? "/var/microbox/hooks.md5" }
end

aws_hooks_md5 = execute "aws hooks md5" do
  command "curl \
    -f \
    -k \
    https://s3.amazonaws.com/tools.microbox.cloud/hooks/portal-stable.md5 \
      | tee /tmp/hooks.md5"
end

if local_hooks_md5 != aws_hooks_md5
  execute "update hooks" do
    command "curl \
      -f \
      -k \
      https://s3.amazonaws.com/tools.microbox.cloud/hooks/portal-stable.tgz \
        | tar -xz -C /opt/microbox/hooks"
  end

  execute "Finalize update" do
    command "mv /tmp/hooks.md5 /var/microbox/hooks.md5"
  end
end
